#!/bin/bash

alias @="source ~/.zshrc"
alias del="trash"
alias grep="grep --color"
alias em="TERM=xterm-24bit emacs -nw"
alias dc="docker"
alias dcc="docker-compose"

ls() {
  if [[ $# -eq 0 ]] ; then
    exa -1 -s ext
  else
    exa "$@"
  fi
}

