#!/bin/bash

alias @="source ~/.zshrc"
alias del="trash"

ls() {
  if [[ $# -eq 0 ]] ; then
    exa -1 -s ext
  else
    exa "$@"
  fi
}

em() {
  if [ -x "$(command -v autohotkey.exe)" ]; then
    emacsclient -n $@
    powershell.exe -c "echo '$(cat ~/dotfiles/roles/emacs/files/focus.ahk)' | autohotkey.exe *"
  else
    emacsclient -n $@;
  fi
}
